// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type {
    InstrumentsServiceBondByData,
    InstrumentsServiceBondByErrors,
    InstrumentsServiceBondByResponses,
    InstrumentsServiceBondsData,
    InstrumentsServiceBondsErrors,
    InstrumentsServiceBondsResponses,
    InstrumentsServiceCreateFavoriteGroupData,
    InstrumentsServiceCreateFavoriteGroupErrors,
    InstrumentsServiceCreateFavoriteGroupResponses,
    InstrumentsServiceCurrenciesData,
    InstrumentsServiceCurrenciesErrors,
    InstrumentsServiceCurrenciesResponses,
    InstrumentsServiceCurrencyByData,
    InstrumentsServiceCurrencyByErrors,
    InstrumentsServiceCurrencyByResponses,
    InstrumentsServiceDeleteFavoriteGroupData,
    InstrumentsServiceDeleteFavoriteGroupErrors,
    InstrumentsServiceDeleteFavoriteGroupResponses,
    InstrumentsServiceEditFavoritesData,
    InstrumentsServiceEditFavoritesErrors,
    InstrumentsServiceEditFavoritesResponses,
    InstrumentsServiceEtfByData,
    InstrumentsServiceEtfByErrors,
    InstrumentsServiceEtfByResponses,
    InstrumentsServiceEtfsData,
    InstrumentsServiceEtfsErrors,
    InstrumentsServiceEtfsResponses,
    InstrumentsServiceFindInstrumentData,
    InstrumentsServiceFindInstrumentErrors,
    InstrumentsServiceFindInstrumentResponses,
    InstrumentsServiceFutureByData,
    InstrumentsServiceFutureByErrors,
    InstrumentsServiceFutureByResponses,
    InstrumentsServiceFuturesData,
    InstrumentsServiceFuturesErrors,
    InstrumentsServiceFuturesResponses,
    InstrumentsServiceGetAccruedInterestsData,
    InstrumentsServiceGetAccruedInterestsErrors,
    InstrumentsServiceGetAccruedInterestsResponses,
    InstrumentsServiceGetAssetByData,
    InstrumentsServiceGetAssetByErrors,
    InstrumentsServiceGetAssetByResponses,
    InstrumentsServiceGetAssetFundamentalsData,
    InstrumentsServiceGetAssetFundamentalsErrors,
    InstrumentsServiceGetAssetFundamentalsResponses,
    InstrumentsServiceGetAssetReportsData,
    InstrumentsServiceGetAssetReportsErrors,
    InstrumentsServiceGetAssetReportsResponses,
    InstrumentsServiceGetAssetsData,
    InstrumentsServiceGetAssetsErrors,
    InstrumentsServiceGetAssetsResponses,
    InstrumentsServiceGetBondCouponsData,
    InstrumentsServiceGetBondCouponsErrors,
    InstrumentsServiceGetBondCouponsResponses,
    InstrumentsServiceGetBondEventsData,
    InstrumentsServiceGetBondEventsErrors,
    InstrumentsServiceGetBondEventsResponses,
    InstrumentsServiceGetBrandByData,
    InstrumentsServiceGetBrandByErrors,
    InstrumentsServiceGetBrandByResponses,
    InstrumentsServiceGetBrandsData,
    InstrumentsServiceGetBrandsErrors,
    InstrumentsServiceGetBrandsResponses,
    InstrumentsServiceGetConsensusForecastsData,
    InstrumentsServiceGetConsensusForecastsErrors,
    InstrumentsServiceGetConsensusForecastsResponses,
    InstrumentsServiceGetCountriesData,
    InstrumentsServiceGetCountriesErrors,
    InstrumentsServiceGetCountriesResponses,
    InstrumentsServiceGetDividendsData,
    InstrumentsServiceGetDividendsErrors,
    InstrumentsServiceGetDividendsResponses,
    InstrumentsServiceGetFavoriteGroupsData,
    InstrumentsServiceGetFavoriteGroupsErrors,
    InstrumentsServiceGetFavoriteGroupsResponses,
    InstrumentsServiceGetFavoritesData,
    InstrumentsServiceGetFavoritesErrors,
    InstrumentsServiceGetFavoritesResponses,
    InstrumentsServiceGetForecastByData,
    InstrumentsServiceGetForecastByErrors,
    InstrumentsServiceGetForecastByResponses,
    InstrumentsServiceGetFuturesMarginData,
    InstrumentsServiceGetFuturesMarginErrors,
    InstrumentsServiceGetFuturesMarginResponses,
    InstrumentsServiceGetInsiderDealsData,
    InstrumentsServiceGetInsiderDealsErrors,
    InstrumentsServiceGetInsiderDealsResponses,
    InstrumentsServiceGetInstrumentByData,
    InstrumentsServiceGetInstrumentByErrors,
    InstrumentsServiceGetInstrumentByResponses,
    InstrumentsServiceGetRiskRatesData,
    InstrumentsServiceGetRiskRatesErrors,
    InstrumentsServiceGetRiskRatesResponses,
    InstrumentsServiceIndicativesData,
    InstrumentsServiceIndicativesErrors,
    InstrumentsServiceIndicativesResponses,
    InstrumentsServiceOptionByData,
    InstrumentsServiceOptionByErrors,
    InstrumentsServiceOptionByResponses,
    InstrumentsServiceOptionsByData,
    InstrumentsServiceOptionsByErrors,
    InstrumentsServiceOptionsByResponses,
    InstrumentsServiceOptionsData,
    InstrumentsServiceOptionsErrors,
    InstrumentsServiceOptionsResponses,
    InstrumentsServiceShareByData,
    InstrumentsServiceShareByErrors,
    InstrumentsServiceShareByResponses,
    InstrumentsServiceSharesData,
    InstrumentsServiceSharesErrors,
    InstrumentsServiceSharesResponses,
    InstrumentsServiceStructuredNoteByData,
    InstrumentsServiceStructuredNoteByErrors,
    InstrumentsServiceStructuredNoteByResponses,
    InstrumentsServiceStructuredNotesData,
    InstrumentsServiceStructuredNotesErrors,
    InstrumentsServiceStructuredNotesResponses,
    InstrumentsServiceTradingSchedulesData,
    InstrumentsServiceTradingSchedulesErrors,
    InstrumentsServiceTradingSchedulesResponses,
    MarketDataServiceGetCandlesData,
    MarketDataServiceGetCandlesErrors,
    MarketDataServiceGetCandlesResponses,
    MarketDataServiceGetClosePricesData,
    MarketDataServiceGetClosePricesErrors,
    MarketDataServiceGetClosePricesResponses,
    MarketDataServiceGetLastPricesData,
    MarketDataServiceGetLastPricesErrors,
    MarketDataServiceGetLastPricesResponses,
    MarketDataServiceGetLastTradesData,
    MarketDataServiceGetLastTradesErrors,
    MarketDataServiceGetLastTradesResponses,
    MarketDataServiceGetMarketValuesData,
    MarketDataServiceGetMarketValuesErrors,
    MarketDataServiceGetMarketValuesResponses,
    MarketDataServiceGetOrderBookData,
    MarketDataServiceGetOrderBookErrors,
    MarketDataServiceGetOrderBookResponses,
    MarketDataServiceGetTechAnalysisData,
    MarketDataServiceGetTechAnalysisErrors,
    MarketDataServiceGetTechAnalysisResponses,
    MarketDataServiceGetTradingStatusData,
    MarketDataServiceGetTradingStatusErrors,
    MarketDataServiceGetTradingStatusesData,
    MarketDataServiceGetTradingStatusesErrors,
    MarketDataServiceGetTradingStatusesResponses,
    MarketDataServiceGetTradingStatusResponses,
    MarketDataStreamServiceMarketDataServerSideStreamData,
    MarketDataStreamServiceMarketDataServerSideStreamErrors,
    MarketDataStreamServiceMarketDataServerSideStreamResponses,
    MarketDataStreamServiceMarketDataStreamData,
    MarketDataStreamServiceMarketDataStreamErrors,
    MarketDataStreamServiceMarketDataStreamResponses,
    OperationsServiceGetBrokerReportData,
    OperationsServiceGetBrokerReportErrors,
    OperationsServiceGetBrokerReportResponses,
    OperationsServiceGetDividendsForeignIssuerData,
    OperationsServiceGetDividendsForeignIssuerErrors,
    OperationsServiceGetDividendsForeignIssuerResponses,
    OperationsServiceGetOperationsByCursorData,
    OperationsServiceGetOperationsByCursorErrors,
    OperationsServiceGetOperationsByCursorResponses,
    OperationsServiceGetOperationsData,
    OperationsServiceGetOperationsErrors,
    OperationsServiceGetOperationsResponses,
    OperationsServiceGetPortfolioData,
    OperationsServiceGetPortfolioErrors,
    OperationsServiceGetPortfolioResponses,
    OperationsServiceGetPositionsData,
    OperationsServiceGetPositionsErrors,
    OperationsServiceGetPositionsResponses,
    OperationsServiceGetWithdrawLimitsData,
    OperationsServiceGetWithdrawLimitsErrors,
    OperationsServiceGetWithdrawLimitsResponses,
    OperationsStreamServicePortfolioStreamData,
    OperationsStreamServicePortfolioStreamErrors,
    OperationsStreamServicePortfolioStreamResponses,
    OperationsStreamServicePositionsStreamData,
    OperationsStreamServicePositionsStreamErrors,
    OperationsStreamServicePositionsStreamResponses,
    OrdersServiceCancelOrderData,
    OrdersServiceCancelOrderErrors,
    OrdersServiceCancelOrderResponses,
    OrdersServiceGetMaxLotsData,
    OrdersServiceGetMaxLotsErrors,
    OrdersServiceGetMaxLotsResponses,
    OrdersServiceGetOrderPriceData,
    OrdersServiceGetOrderPriceErrors,
    OrdersServiceGetOrderPriceResponses,
    OrdersServiceGetOrdersData,
    OrdersServiceGetOrdersErrors,
    OrdersServiceGetOrdersResponses,
    OrdersServiceGetOrderStateData,
    OrdersServiceGetOrderStateErrors,
    OrdersServiceGetOrderStateResponses,
    OrdersServicePostOrderAsyncData,
    OrdersServicePostOrderAsyncErrors,
    OrdersServicePostOrderAsyncResponses,
    OrdersServicePostOrderData,
    OrdersServicePostOrderErrors,
    OrdersServicePostOrderResponses,
    OrdersServiceReplaceOrderData,
    OrdersServiceReplaceOrderErrors,
    OrdersServiceReplaceOrderResponses,
    OrdersStreamServiceOrderStateStreamData,
    OrdersStreamServiceOrderStateStreamErrors,
    OrdersStreamServiceOrderStateStreamResponses,
    OrdersStreamServiceTradesStreamData,
    OrdersStreamServiceTradesStreamErrors,
    OrdersStreamServiceTradesStreamResponses,
    SandboxServiceCancelSandboxOrderData,
    SandboxServiceCancelSandboxOrderErrors,
    SandboxServiceCancelSandboxOrderResponses,
    SandboxServiceCancelSandboxStopOrderData,
    SandboxServiceCancelSandboxStopOrderErrors,
    SandboxServiceCancelSandboxStopOrderResponses,
    SandboxServiceCloseSandboxAccountData,
    SandboxServiceCloseSandboxAccountErrors,
    SandboxServiceCloseSandboxAccountResponses,
    SandboxServiceGetSandboxAccountsData,
    SandboxServiceGetSandboxAccountsErrors,
    SandboxServiceGetSandboxAccountsResponses,
    SandboxServiceGetSandboxMaxLotsData,
    SandboxServiceGetSandboxMaxLotsErrors,
    SandboxServiceGetSandboxMaxLotsResponses,
    SandboxServiceGetSandboxOperationsByCursorData,
    SandboxServiceGetSandboxOperationsByCursorErrors,
    SandboxServiceGetSandboxOperationsByCursorResponses,
    SandboxServiceGetSandboxOperationsData,
    SandboxServiceGetSandboxOperationsErrors,
    SandboxServiceGetSandboxOperationsResponses,
    SandboxServiceGetSandboxOrderPriceData,
    SandboxServiceGetSandboxOrderPriceErrors,
    SandboxServiceGetSandboxOrderPriceResponses,
    SandboxServiceGetSandboxOrdersData,
    SandboxServiceGetSandboxOrdersErrors,
    SandboxServiceGetSandboxOrdersResponses,
    SandboxServiceGetSandboxOrderStateData,
    SandboxServiceGetSandboxOrderStateErrors,
    SandboxServiceGetSandboxOrderStateResponses,
    SandboxServiceGetSandboxPortfolioData,
    SandboxServiceGetSandboxPortfolioErrors,
    SandboxServiceGetSandboxPortfolioResponses,
    SandboxServiceGetSandboxPositionsData,
    SandboxServiceGetSandboxPositionsErrors,
    SandboxServiceGetSandboxPositionsResponses,
    SandboxServiceGetSandboxStopOrdersData,
    SandboxServiceGetSandboxStopOrdersErrors,
    SandboxServiceGetSandboxStopOrdersResponses,
    SandboxServiceGetSandboxWithdrawLimitsData,
    SandboxServiceGetSandboxWithdrawLimitsErrors,
    SandboxServiceGetSandboxWithdrawLimitsResponses,
    SandboxServiceOpenSandboxAccountData,
    SandboxServiceOpenSandboxAccountErrors,
    SandboxServiceOpenSandboxAccountResponses,
    SandboxServicePostSandboxOrderAsyncData,
    SandboxServicePostSandboxOrderAsyncErrors,
    SandboxServicePostSandboxOrderAsyncResponses,
    SandboxServicePostSandboxOrderData,
    SandboxServicePostSandboxOrderErrors,
    SandboxServicePostSandboxOrderResponses,
    SandboxServicePostSandboxStopOrderData,
    SandboxServicePostSandboxStopOrderErrors,
    SandboxServicePostSandboxStopOrderResponses,
    SandboxServiceReplaceSandboxOrderData,
    SandboxServiceReplaceSandboxOrderErrors,
    SandboxServiceReplaceSandboxOrderResponses,
    SandboxServiceSandboxPayInData,
    SandboxServiceSandboxPayInErrors,
    SandboxServiceSandboxPayInResponses,
    SignalServiceGetSignalsData,
    SignalServiceGetSignalsErrors,
    SignalServiceGetSignalsResponses,
    SignalServiceGetStrategiesData,
    SignalServiceGetStrategiesErrors,
    SignalServiceGetStrategiesResponses,
    StopOrdersServiceCancelStopOrderData,
    StopOrdersServiceCancelStopOrderErrors,
    StopOrdersServiceCancelStopOrderResponses,
    StopOrdersServiceGetStopOrdersData,
    StopOrdersServiceGetStopOrdersErrors,
    StopOrdersServiceGetStopOrdersResponses,
    StopOrdersServicePostStopOrderData,
    StopOrdersServicePostStopOrderErrors,
    StopOrdersServicePostStopOrderResponses,
    UsersServiceCurrencyTransferData,
    UsersServiceCurrencyTransferErrors,
    UsersServiceCurrencyTransferResponses,
    UsersServiceGetAccountsData,
    UsersServiceGetAccountsErrors,
    UsersServiceGetAccountsResponses,
    UsersServiceGetBankAccountsData,
    UsersServiceGetBankAccountsErrors,
    UsersServiceGetBankAccountsResponses,
    UsersServiceGetInfoData,
    UsersServiceGetInfoErrors,
    UsersServiceGetInfoResponses,
    UsersServiceGetMarginAttributesData,
    UsersServiceGetMarginAttributesErrors,
    UsersServiceGetMarginAttributesResponses,
    UsersServiceGetUserTariffData,
    UsersServiceGetUserTariffErrors,
    UsersServiceGetUserTariffResponses,
} from './types.gen.js';

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * BondBy — получить облигацию по ее идентификатору
 */
export const instrumentsServiceBondBy = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceBondByData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceBondByResponses,
        InstrumentsServiceBondByErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/BondBy',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * Bonds — список облигаций
 */
export const instrumentsServiceBonds = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceBondsData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceBondsResponses,
        InstrumentsServiceBondsErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/Bonds',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * CreateFavoriteGroup — создать новую группу избранных инструментов
 */
export const instrumentsServiceCreateFavoriteGroup = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceCreateFavoriteGroupData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceCreateFavoriteGroupResponses,
        InstrumentsServiceCreateFavoriteGroupErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/CreateFavoriteGroup',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * Currencies — список валют
 */
export const instrumentsServiceCurrencies = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceCurrenciesData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceCurrenciesResponses,
        InstrumentsServiceCurrenciesErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/Currencies',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * CurrencyBy — получить валюту по ее идентификатору
 */
export const instrumentsServiceCurrencyBy = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceCurrencyByData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceCurrencyByResponses,
        InstrumentsServiceCurrencyByErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/CurrencyBy',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * DeleteFavoriteGroup — удалить группу избранных инструментов
 */
export const instrumentsServiceDeleteFavoriteGroup = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceDeleteFavoriteGroupData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceDeleteFavoriteGroupResponses,
        InstrumentsServiceDeleteFavoriteGroupErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/DeleteFavoriteGroup',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * EditFavorites — отредактировать список избранных инструментов
 */
export const instrumentsServiceEditFavorites = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceEditFavoritesData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceEditFavoritesResponses,
        InstrumentsServiceEditFavoritesErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/EditFavorites',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * EtfBy — получить инвестиционный фонд по его идентификатору
 */
export const instrumentsServiceEtfBy = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceEtfByData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceEtfByResponses,
        InstrumentsServiceEtfByErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/EtfBy',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * Etfs — список инвестиционных фондов
 */
export const instrumentsServiceEtfs = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceEtfsData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceEtfsResponses,
        InstrumentsServiceEtfsErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/Etfs',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * FindInstrument — найти инструмент
 */
export const instrumentsServiceFindInstrument = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceFindInstrumentData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceFindInstrumentResponses,
        InstrumentsServiceFindInstrumentErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/FindInstrument',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * FutureBy — получить фьючерс по его идентификатору
 */
export const instrumentsServiceFutureBy = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceFutureByData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceFutureByResponses,
        InstrumentsServiceFutureByErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/FutureBy',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * Futures — список фьючерсов
 */
export const instrumentsServiceFutures = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceFuturesData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceFuturesResponses,
        InstrumentsServiceFuturesErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/Futures',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetAccruedInterests — накопленный купонный доход по облигации
 */
export const instrumentsServiceGetAccruedInterests = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceGetAccruedInterestsData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceGetAccruedInterestsResponses,
        InstrumentsServiceGetAccruedInterestsErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetAccruedInterests',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetAssetBy — получить актив по его идентификатору
 */
export const instrumentsServiceGetAssetBy = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceGetAssetByData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceGetAssetByResponses,
        InstrumentsServiceGetAssetByErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetAssetBy',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetAssetFundamentals — фундаментальные показатели по активу
 */
export const instrumentsServiceGetAssetFundamentals = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceGetAssetFundamentalsData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceGetAssetFundamentalsResponses,
        InstrumentsServiceGetAssetFundamentalsErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetAssetFundamentals',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetAssetReports — расписания выхода отчетностей эмитентов
 */
export const instrumentsServiceGetAssetReports = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceGetAssetReportsData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceGetAssetReportsResponses,
        InstrumentsServiceGetAssetReportsErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetAssetReports',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetAssets — список активов
 *
 * Метод работает для всех инструментов, кроме срочных — фьючерсов и опционов
 */
export const instrumentsServiceGetAssets = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceGetAssetsData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceGetAssetsResponses,
        InstrumentsServiceGetAssetsErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetAssets',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetBondCoupons — график выплат купонов по облигации
 */
export const instrumentsServiceGetBondCoupons = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceGetBondCouponsData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceGetBondCouponsResponses,
        InstrumentsServiceGetBondCouponsErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetBondCoupons',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetBondEvents — события по облигации
 */
export const instrumentsServiceGetBondEvents = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceGetBondEventsData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceGetBondEventsResponses,
        InstrumentsServiceGetBondEventsErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetBondEvents',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetBrandBy — получить бренд по его идентификатору
 */
export const instrumentsServiceGetBrandBy = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceGetBrandByData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceGetBrandByResponses,
        InstrumentsServiceGetBrandByErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetBrandBy',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetBrands — список брендов
 */
export const instrumentsServiceGetBrands = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceGetBrandsData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceGetBrandsResponses,
        InstrumentsServiceGetBrandsErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetBrands',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetConsensusForecasts — мнения аналитиков по инструменту
 */
export const instrumentsServiceGetConsensusForecasts = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceGetConsensusForecastsData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceGetConsensusForecastsResponses,
        InstrumentsServiceGetConsensusForecastsErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetConsensusForecasts',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetCountries — список стран
 */
export const instrumentsServiceGetCountries = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceGetCountriesData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceGetCountriesResponses,
        InstrumentsServiceGetCountriesErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetCountries',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetDividends — события выплаты дивидендов по инструменту
 */
export const instrumentsServiceGetDividends = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceGetDividendsData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceGetDividendsResponses,
        InstrumentsServiceGetDividendsErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetDividends',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetFavoriteGroups — список групп избранных инструментов
 */
export const instrumentsServiceGetFavoriteGroups = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceGetFavoriteGroupsData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceGetFavoriteGroupsResponses,
        InstrumentsServiceGetFavoriteGroupsErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetFavoriteGroups',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetFavorites — получить список избранных инструментов
 */
export const instrumentsServiceGetFavorites = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceGetFavoritesData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceGetFavoritesResponses,
        InstrumentsServiceGetFavoritesErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetFavorites',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetForecastBy — прогнозы инвестдомов по инструменту
 */
export const instrumentsServiceGetForecastBy = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceGetForecastByData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceGetForecastByResponses,
        InstrumentsServiceGetForecastByErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetForecastBy',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetFuturesMargin — размера гарантийного обеспечения по фьючерсам
 */
export const instrumentsServiceGetFuturesMargin = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceGetFuturesMarginData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceGetFuturesMarginResponses,
        InstrumentsServiceGetFuturesMarginErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetFuturesMargin',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetInsiderDeals —  сделки инсайдеров по инструментам
 */
export const instrumentsServiceGetInsiderDeals = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceGetInsiderDealsData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceGetInsiderDealsResponses,
        InstrumentsServiceGetInsiderDealsErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetInsiderDeals',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetInstrumentBy — основная информация об инструменте
 */
export const instrumentsServiceGetInstrumentBy = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceGetInstrumentByData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceGetInstrumentByResponses,
        InstrumentsServiceGetInstrumentByErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetInstrumentBy',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetRiskRates — ставки риска по инструменту
 */
export const instrumentsServiceGetRiskRates = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceGetRiskRatesData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceGetRiskRatesResponses,
        InstrumentsServiceGetRiskRatesErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetRiskRates',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * Indicatives — индикативные инструменты — индексы, товары и другие
 */
export const instrumentsServiceIndicatives = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceIndicativesData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceIndicativesResponses,
        InstrumentsServiceIndicativesErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/Indicatives',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * OptionBy — получить опцион по его идентификатору
 */
export const instrumentsServiceOptionBy = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceOptionByData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceOptionByResponses,
        InstrumentsServiceOptionByErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/OptionBy',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * Deprecated Options — список опционов
 */
export const instrumentsServiceOptions = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceOptionsData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceOptionsResponses,
        InstrumentsServiceOptionsErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/Options',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * OptionsBy — список опционов
 */
export const instrumentsServiceOptionsBy = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceOptionsByData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceOptionsByResponses,
        InstrumentsServiceOptionsByErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/OptionsBy',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * ShareBy — получить акцию по ее идентификатору
 */
export const instrumentsServiceShareBy = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceShareByData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceShareByResponses,
        InstrumentsServiceShareByErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/ShareBy',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * Shares — список акций
 */
export const instrumentsServiceShares = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceSharesData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceSharesResponses,
        InstrumentsServiceSharesErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/Shares',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * StructuredNoteBy — получить структурную ноту по ее идентификатору
 */
export const instrumentsServiceStructuredNoteBy = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceStructuredNoteByData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceStructuredNoteByResponses,
        InstrumentsServiceStructuredNoteByErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/StructuredNoteBy',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * StructuredNotes — список структурных нот
 */
export const instrumentsServiceStructuredNotes = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceStructuredNotesData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceStructuredNotesResponses,
        InstrumentsServiceStructuredNotesErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/StructuredNotes',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * TradingSchedules — расписания торговых площадок
 */
export const instrumentsServiceTradingSchedules = <ThrowOnError extends boolean = true>(
    options: Options<InstrumentsServiceTradingSchedulesData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        InstrumentsServiceTradingSchedulesResponses,
        InstrumentsServiceTradingSchedulesErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/TradingSchedules',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetCandles — исторические свечи по инструменту
 */
export const marketDataServiceGetCandles = <ThrowOnError extends boolean = true>(
    options: Options<MarketDataServiceGetCandlesData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        MarketDataServiceGetCandlesResponses,
        MarketDataServiceGetCandlesErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.MarketDataService/GetCandles',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetClosePrices — цены закрытия торговой сессии по инструментам
 */
export const marketDataServiceGetClosePrices = <ThrowOnError extends boolean = true>(
    options: Options<MarketDataServiceGetClosePricesData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        MarketDataServiceGetClosePricesResponses,
        MarketDataServiceGetClosePricesErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.MarketDataService/GetClosePrices',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetLastPrices — цены последних сделок по инструментам
 */
export const marketDataServiceGetLastPrices = <ThrowOnError extends boolean = true>(
    options: Options<MarketDataServiceGetLastPricesData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        MarketDataServiceGetLastPricesResponses,
        MarketDataServiceGetLastPricesErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.MarketDataService/GetLastPrices',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetLastTrades — обезличенные сделки
 *
 * Обезличенные сделки по инструменту. Метод гарантирует получение информации за последний час.
 */
export const marketDataServiceGetLastTrades = <ThrowOnError extends boolean = true>(
    options: Options<MarketDataServiceGetLastTradesData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        MarketDataServiceGetLastTradesResponses,
        MarketDataServiceGetLastTradesErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.MarketDataService/GetLastTrades',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetMarketValues — рыночные данные по инструментам
 */
export const marketDataServiceGetMarketValues = <ThrowOnError extends boolean = true>(
    options: Options<MarketDataServiceGetMarketValuesData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        MarketDataServiceGetMarketValuesResponses,
        MarketDataServiceGetMarketValuesErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.MarketDataService/GetMarketValues',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetOrderBook — стакан по инструменту
 */
export const marketDataServiceGetOrderBook = <ThrowOnError extends boolean = true>(
    options: Options<MarketDataServiceGetOrderBookData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        MarketDataServiceGetOrderBookResponses,
        MarketDataServiceGetOrderBookErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.MarketDataService/GetOrderBook',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetTechAnalysis — технические индикаторы по инструменту
 */
export const marketDataServiceGetTechAnalysis = <ThrowOnError extends boolean = true>(
    options: Options<MarketDataServiceGetTechAnalysisData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        MarketDataServiceGetTechAnalysisResponses,
        MarketDataServiceGetTechAnalysisErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.MarketDataService/GetTechAnalysis',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetTradingStatus — статус торгов по инструменту
 */
export const marketDataServiceGetTradingStatus = <ThrowOnError extends boolean = true>(
    options: Options<MarketDataServiceGetTradingStatusData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        MarketDataServiceGetTradingStatusResponses,
        MarketDataServiceGetTradingStatusErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.MarketDataService/GetTradingStatus',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetTradingStatuses — статус торгов по инструментам
 */
export const marketDataServiceGetTradingStatuses = <ThrowOnError extends boolean = true>(
    options: Options<MarketDataServiceGetTradingStatusesData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        MarketDataServiceGetTradingStatusesResponses,
        MarketDataServiceGetTradingStatusesErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.MarketDataService/GetTradingStatuses',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * MarketDataServerSideStream — server-side стрим предоставления биржевой информации
 */
export const marketDataStreamServiceMarketDataServerSideStream = <
    ThrowOnError extends boolean = true,
>(
    options: Options<MarketDataStreamServiceMarketDataServerSideStreamData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        MarketDataStreamServiceMarketDataServerSideStreamResponses,
        MarketDataStreamServiceMarketDataServerSideStreamErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.MarketDataStreamService/MarketDataServerSideStream',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * MarketDataStream — bidirectional стрим предоставления биржевой информации
 */
export const marketDataStreamServiceMarketDataStream = <ThrowOnError extends boolean = true>(
    options: Options<MarketDataStreamServiceMarketDataStreamData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        MarketDataStreamServiceMarketDataStreamResponses,
        MarketDataStreamServiceMarketDataStreamErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.MarketDataStreamService/MarketDataStream',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetBrokerReport — брокерский отчет.
 */
export const operationsServiceGetBrokerReport = <ThrowOnError extends boolean = true>(
    options: Options<OperationsServiceGetBrokerReportData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        OperationsServiceGetBrokerReportResponses,
        OperationsServiceGetBrokerReportErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.OperationsService/GetBrokerReport',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetDividendsForeignIssuer — отчет «Справка о доходах за пределами РФ»
 */
export const operationsServiceGetDividendsForeignIssuer = <ThrowOnError extends boolean = true>(
    options: Options<OperationsServiceGetDividendsForeignIssuerData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        OperationsServiceGetDividendsForeignIssuerResponses,
        OperationsServiceGetDividendsForeignIssuerErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.OperationsService/GetDividendsForeignIssuer',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetOperations — список операций по счету
 *
 * При работе с методом учитывайте [особенности взаимодействия](/invest/services/operations/operations_problems).
 */
export const operationsServiceGetOperations = <ThrowOnError extends boolean = true>(
    options: Options<OperationsServiceGetOperationsData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        OperationsServiceGetOperationsResponses,
        OperationsServiceGetOperationsErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.OperationsService/GetOperations',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetOperationsByCursor — список операций по счету с пагинацией
 *
 * При работе с методом учитывайте [особенности взаимодействия](/invest/services/operations/operations_problems).
 */
export const operationsServiceGetOperationsByCursor = <ThrowOnError extends boolean = true>(
    options: Options<OperationsServiceGetOperationsByCursorData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        OperationsServiceGetOperationsByCursorResponses,
        OperationsServiceGetOperationsByCursorErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.OperationsService/GetOperationsByCursor',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetPortfolio — портфель по счету
 */
export const operationsServiceGetPortfolio = <ThrowOnError extends boolean = true>(
    options: Options<OperationsServiceGetPortfolioData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        OperationsServiceGetPortfolioResponses,
        OperationsServiceGetPortfolioErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.OperationsService/GetPortfolio',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetPositions — список позиций по счету
 */
export const operationsServiceGetPositions = <ThrowOnError extends boolean = true>(
    options: Options<OperationsServiceGetPositionsData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        OperationsServiceGetPositionsResponses,
        OperationsServiceGetPositionsErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.OperationsService/GetPositions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetWithdrawLimits — доступный остаток для вывода средств
 */
export const operationsServiceGetWithdrawLimits = <ThrowOnError extends boolean = true>(
    options: Options<OperationsServiceGetWithdrawLimitsData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        OperationsServiceGetWithdrawLimitsResponses,
        OperationsServiceGetWithdrawLimitsErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.OperationsService/GetWithdrawLimits',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * PortfolioStream — стрим обновлений портфеля
 */
export const operationsStreamServicePortfolioStream = <ThrowOnError extends boolean = true>(
    options: Options<OperationsStreamServicePortfolioStreamData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        OperationsStreamServicePortfolioStreamResponses,
        OperationsStreamServicePortfolioStreamErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.OperationsStreamService/PortfolioStream',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * PositionsStream — стрим обновлений информации по изменению позиций портфеля
 */
export const operationsStreamServicePositionsStream = <ThrowOnError extends boolean = true>(
    options: Options<OperationsStreamServicePositionsStreamData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        OperationsStreamServicePositionsStreamResponses,
        OperationsStreamServicePositionsStreamErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.OperationsStreamService/PositionsStream',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * CancelOrder — отменить заявку
 */
export const ordersServiceCancelOrder = <ThrowOnError extends boolean = true>(
    options: Options<OrdersServiceCancelOrderData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        OrdersServiceCancelOrderResponses,
        OrdersServiceCancelOrderErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.OrdersService/CancelOrder',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetMaxLots — расчет количества доступных для покупки/продажи лотов
 */
export const ordersServiceGetMaxLots = <ThrowOnError extends boolean = true>(
    options: Options<OrdersServiceGetMaxLotsData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        OrdersServiceGetMaxLotsResponses,
        OrdersServiceGetMaxLotsErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.OrdersService/GetMaxLots',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetOrderPrice — получить предварительную стоимость для лимитной заявки
 */
export const ordersServiceGetOrderPrice = <ThrowOnError extends boolean = true>(
    options: Options<OrdersServiceGetOrderPriceData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        OrdersServiceGetOrderPriceResponses,
        OrdersServiceGetOrderPriceErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.OrdersService/GetOrderPrice',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetOrderState — получить статус торгового поручения
 */
export const ordersServiceGetOrderState = <ThrowOnError extends boolean = true>(
    options: Options<OrdersServiceGetOrderStateData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        OrdersServiceGetOrderStateResponses,
        OrdersServiceGetOrderStateErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.OrdersService/GetOrderState',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetOrders — получить список активных заявок по счету
 */
export const ordersServiceGetOrders = <ThrowOnError extends boolean = true>(
    options: Options<OrdersServiceGetOrdersData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        OrdersServiceGetOrdersResponses,
        OrdersServiceGetOrdersErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.OrdersService/GetOrders',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * PostOrder — выставить заявку
 */
export const ordersServicePostOrder = <ThrowOnError extends boolean = true>(
    options: Options<OrdersServicePostOrderData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        OrdersServicePostOrderResponses,
        OrdersServicePostOrderErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.OrdersService/PostOrder',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * PostOrderAsync — выставить заявку асинхронным методом
 *
 * Особенности работы приведены в [статье](/invest/services/orders/async).
 */
export const ordersServicePostOrderAsync = <ThrowOnError extends boolean = true>(
    options: Options<OrdersServicePostOrderAsyncData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        OrdersServicePostOrderAsyncResponses,
        OrdersServicePostOrderAsyncErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.OrdersService/PostOrderAsync',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * ReplaceOrder — изменить выставленную заявку
 */
export const ordersServiceReplaceOrder = <ThrowOnError extends boolean = true>(
    options: Options<OrdersServiceReplaceOrderData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        OrdersServiceReplaceOrderResponses,
        OrdersServiceReplaceOrderErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.OrdersService/ReplaceOrder',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * OrderStateStream — стрим поручений пользователя
 *
 * Перед работой прочитайте [статью](/invest/services/orders/orders_state_stream).
 */
export const ordersStreamServiceOrderStateStream = <ThrowOnError extends boolean = true>(
    options: Options<OrdersStreamServiceOrderStateStreamData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        OrdersStreamServiceOrderStateStreamResponses,
        OrdersStreamServiceOrderStateStreamErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.OrdersStreamService/OrderStateStream',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * TradesStream — стрим сделок пользователя
 */
export const ordersStreamServiceTradesStream = <ThrowOnError extends boolean = true>(
    options: Options<OrdersStreamServiceTradesStreamData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        OrdersStreamServiceTradesStreamResponses,
        OrdersStreamServiceTradesStreamErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.OrdersStreamService/TradesStream',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * CancelSandboxOrder — отменить заявку
 */
export const sandboxServiceCancelSandboxOrder = <ThrowOnError extends boolean = true>(
    options: Options<SandboxServiceCancelSandboxOrderData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        SandboxServiceCancelSandboxOrderResponses,
        SandboxServiceCancelSandboxOrderErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.SandboxService/CancelSandboxOrder',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * CancelSandboxStopOrder — отменить стоп-заявку
 */
export const sandboxServiceCancelSandboxStopOrder = <ThrowOnError extends boolean = true>(
    options: Options<SandboxServiceCancelSandboxStopOrderData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        SandboxServiceCancelSandboxStopOrderResponses,
        SandboxServiceCancelSandboxStopOrderErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.SandboxService/CancelSandboxStopOrder',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * CloseSandboxAccount — закрыть счет
 */
export const sandboxServiceCloseSandboxAccount = <ThrowOnError extends boolean = true>(
    options: Options<SandboxServiceCloseSandboxAccountData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        SandboxServiceCloseSandboxAccountResponses,
        SandboxServiceCloseSandboxAccountErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.SandboxService/CloseSandboxAccount',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetSandboxAccounts — счета пользователя
 */
export const sandboxServiceGetSandboxAccounts = <ThrowOnError extends boolean = true>(
    options: Options<SandboxServiceGetSandboxAccountsData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        SandboxServiceGetSandboxAccountsResponses,
        SandboxServiceGetSandboxAccountsErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxAccounts',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetSandboxMaxLots — расчет количества доступных для покупки/продажи лотов
 */
export const sandboxServiceGetSandboxMaxLots = <ThrowOnError extends boolean = true>(
    options: Options<SandboxServiceGetSandboxMaxLotsData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        SandboxServiceGetSandboxMaxLotsResponses,
        SandboxServiceGetSandboxMaxLotsErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxMaxLots',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetSandboxOperations — список операций по счету
 *
 * При работе с методом учитывайте [особенности взаимодействия](/invest/services/operations/operations_problems).
 */
export const sandboxServiceGetSandboxOperations = <ThrowOnError extends boolean = true>(
    options: Options<SandboxServiceGetSandboxOperationsData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        SandboxServiceGetSandboxOperationsResponses,
        SandboxServiceGetSandboxOperationsErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxOperations',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetSandboxOperationsByCursor — список операций по счету с пагинацией
 *
 * При работе с методом учитывайте [особенности взаимодействия](/invest/services/operations/operations_problems).
 */
export const sandboxServiceGetSandboxOperationsByCursor = <ThrowOnError extends boolean = true>(
    options: Options<SandboxServiceGetSandboxOperationsByCursorData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        SandboxServiceGetSandboxOperationsByCursorResponses,
        SandboxServiceGetSandboxOperationsByCursorErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxOperationsByCursor',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetSandboxOrderPrice — получить предварительную стоимость для лимитной заявки
 */
export const sandboxServiceGetSandboxOrderPrice = <ThrowOnError extends boolean = true>(
    options: Options<SandboxServiceGetSandboxOrderPriceData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        SandboxServiceGetSandboxOrderPriceResponses,
        SandboxServiceGetSandboxOrderPriceErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxOrderPrice',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetSandboxOrderState — получить статус торгового поручения
 */
export const sandboxServiceGetSandboxOrderState = <ThrowOnError extends boolean = true>(
    options: Options<SandboxServiceGetSandboxOrderStateData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        SandboxServiceGetSandboxOrderStateResponses,
        SandboxServiceGetSandboxOrderStateErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxOrderState',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetSandboxOrders — получить список активных заявок по счету
 */
export const sandboxServiceGetSandboxOrders = <ThrowOnError extends boolean = true>(
    options: Options<SandboxServiceGetSandboxOrdersData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        SandboxServiceGetSandboxOrdersResponses,
        SandboxServiceGetSandboxOrdersErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxOrders',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetSandboxPortfolio — портфель по счету
 */
export const sandboxServiceGetSandboxPortfolio = <ThrowOnError extends boolean = true>(
    options: Options<SandboxServiceGetSandboxPortfolioData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        SandboxServiceGetSandboxPortfolioResponses,
        SandboxServiceGetSandboxPortfolioErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxPortfolio',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetSandboxPositions — список позиций по счету
 */
export const sandboxServiceGetSandboxPositions = <ThrowOnError extends boolean = true>(
    options: Options<SandboxServiceGetSandboxPositionsData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        SandboxServiceGetSandboxPositionsResponses,
        SandboxServiceGetSandboxPositionsErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxPositions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetSandboxStopOrders — получить список активных стоп-заявок по счету
 */
export const sandboxServiceGetSandboxStopOrders = <ThrowOnError extends boolean = true>(
    options: Options<SandboxServiceGetSandboxStopOrdersData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        SandboxServiceGetSandboxStopOrdersResponses,
        SandboxServiceGetSandboxStopOrdersErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxStopOrders',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetSandboxWithdrawLimits — доступный остаток для вывода средств
 */
export const sandboxServiceGetSandboxWithdrawLimits = <ThrowOnError extends boolean = true>(
    options: Options<SandboxServiceGetSandboxWithdrawLimitsData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        SandboxServiceGetSandboxWithdrawLimitsResponses,
        SandboxServiceGetSandboxWithdrawLimitsErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxWithdrawLimits',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * OpenSandboxAccount — зарегистрировать счет
 */
export const sandboxServiceOpenSandboxAccount = <ThrowOnError extends boolean = true>(
    options: Options<SandboxServiceOpenSandboxAccountData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        SandboxServiceOpenSandboxAccountResponses,
        SandboxServiceOpenSandboxAccountErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.SandboxService/OpenSandboxAccount',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * PostSandboxOrder — выставить заявку
 */
export const sandboxServicePostSandboxOrder = <ThrowOnError extends boolean = true>(
    options: Options<SandboxServicePostSandboxOrderData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        SandboxServicePostSandboxOrderResponses,
        SandboxServicePostSandboxOrderErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.SandboxService/PostSandboxOrder',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * PostSandboxOrderAsync — выставить заявку асинхронным методом
 *
 * Особенности работы приведены в [статье](/invest/services/orders/async).
 */
export const sandboxServicePostSandboxOrderAsync = <ThrowOnError extends boolean = true>(
    options: Options<SandboxServicePostSandboxOrderAsyncData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        SandboxServicePostSandboxOrderAsyncResponses,
        SandboxServicePostSandboxOrderAsyncErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.SandboxService/PostSandboxOrderAsync',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * PostSandboxStopOrder — выставить стоп-заявку
 */
export const sandboxServicePostSandboxStopOrder = <ThrowOnError extends boolean = true>(
    options: Options<SandboxServicePostSandboxStopOrderData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        SandboxServicePostSandboxStopOrderResponses,
        SandboxServicePostSandboxStopOrderErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.SandboxService/PostSandboxStopOrder',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * ReplaceSandboxOrder — изменить выставленную заявку
 */
export const sandboxServiceReplaceSandboxOrder = <ThrowOnError extends boolean = true>(
    options: Options<SandboxServiceReplaceSandboxOrderData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        SandboxServiceReplaceSandboxOrderResponses,
        SandboxServiceReplaceSandboxOrderErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.SandboxService/ReplaceSandboxOrder',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * SandboxPayIn — пополнить счет.
 */
export const sandboxServiceSandboxPayIn = <ThrowOnError extends boolean = true>(
    options: Options<SandboxServiceSandboxPayInData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        SandboxServiceSandboxPayInResponses,
        SandboxServiceSandboxPayInErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.SandboxService/SandboxPayIn',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetSignals — сигналы
 */
export const signalServiceGetSignals = <ThrowOnError extends boolean = true>(
    options: Options<SignalServiceGetSignalsData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        SignalServiceGetSignalsResponses,
        SignalServiceGetSignalsErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.SignalService/GetSignals',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetStrategies — стратегии
 */
export const signalServiceGetStrategies = <ThrowOnError extends boolean = true>(
    options: Options<SignalServiceGetStrategiesData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        SignalServiceGetStrategiesResponses,
        SignalServiceGetStrategiesErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.SignalService/GetStrategies',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * CancelStopOrder — отменить стоп-заявку
 */
export const stopOrdersServiceCancelStopOrder = <ThrowOnError extends boolean = true>(
    options: Options<StopOrdersServiceCancelStopOrderData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        StopOrdersServiceCancelStopOrderResponses,
        StopOrdersServiceCancelStopOrderErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.StopOrdersService/CancelStopOrder',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetStopOrders — получить список активных стоп-заявок по счету
 */
export const stopOrdersServiceGetStopOrders = <ThrowOnError extends boolean = true>(
    options: Options<StopOrdersServiceGetStopOrdersData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        StopOrdersServiceGetStopOrdersResponses,
        StopOrdersServiceGetStopOrdersErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.StopOrdersService/GetStopOrders',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * PostStopOrder — выставить стоп-заявку
 */
export const stopOrdersServicePostStopOrder = <ThrowOnError extends boolean = true>(
    options: Options<StopOrdersServicePostStopOrderData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        StopOrdersServicePostStopOrderResponses,
        StopOrdersServicePostStopOrderErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.StopOrdersService/PostStopOrder',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * CurrencyTransfer — перевод денежных средств между счетами
 *
 * Перевести денежные средства между брокерскими счетами
 */
export const usersServiceCurrencyTransfer = <ThrowOnError extends boolean = true>(
    options: Options<UsersServiceCurrencyTransferData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        UsersServiceCurrencyTransferResponses,
        UsersServiceCurrencyTransferErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.UsersService/CurrencyTransfer',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetAccounts — счета пользователя
 *
 * Получить список счетов.
 */
export const usersServiceGetAccounts = <ThrowOnError extends boolean = true>(
    options: Options<UsersServiceGetAccountsData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        UsersServiceGetAccountsResponses,
        UsersServiceGetAccountsErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.UsersService/GetAccounts',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetBankAccounts — банковские счета пользователя
 *
 * Получить список счетов пользователя, в том числе и банковских.
 */
export const usersServiceGetBankAccounts = <ThrowOnError extends boolean = true>(
    options: Options<UsersServiceGetBankAccountsData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        UsersServiceGetBankAccountsResponses,
        UsersServiceGetBankAccountsErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.UsersService/GetBankAccounts',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetInfo — информация о пользователе
 *
 * Получить информацию о пользователе: тариф, признак квалификации, пройденные тесты и др.
 */
export const usersServiceGetInfo = <ThrowOnError extends boolean = true>(
    options: Options<UsersServiceGetInfoData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        UsersServiceGetInfoResponses,
        UsersServiceGetInfoErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.UsersService/GetInfo',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetMarginAttributes — маржинальные показатели по счeту
 *
 * Метод позволяет получить маржинальные показатели и ликвидность по заданному счeту.
 */
export const usersServiceGetMarginAttributes = <ThrowOnError extends boolean = true>(
    options: Options<UsersServiceGetMarginAttributesData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        UsersServiceGetMarginAttributesResponses,
        UsersServiceGetMarginAttributesErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.UsersService/GetMarginAttributes',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

/**
 * GetUserTariff — тариф пользователя
 *
 * Получить информацию о текущих лимитах на подклчение, согласно текущему тарифу пользователя.
 */
export const usersServiceGetUserTariff = <ThrowOnError extends boolean = true>(
    options: Options<UsersServiceGetUserTariffData, ThrowOnError>,
) =>
    (options.client ?? client).post<
        UsersServiceGetUserTariffResponses,
        UsersServiceGetUserTariffErrors,
        ThrowOnError
    >({
        responseType: 'json',
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/tinkoff.public.invest.api.contract.v1.UsersService/GetUserTariff',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });
